/**
 * Autogenerated by sync_metrics.py — Real-time Killtime Progression & Manifest
 */
window.KILLTIME_METRICS = {
  "targetWordsPerVolume": 180000,
  "volume1": {
    "title": "Volume I \u2014 The Awakening Storm",
    "draftWords": 213562,
    "draftPct": 100.0,
    "rc1Words": 133124,
    "rc1Pct": 73.96,
    "rc2Pct": 0.0,
    "goldPct": 0.0,
    "totalPct": 54.79,
    "chapterCount": 17
  },
  "volume2": {
    "title": "Volume II \u2014 The Living Current",
    "draftWords": 8893,
    "draftPct": 4.94,
    "rc1Pct": 0.0,
    "rc2Pct": 0.0,
    "goldPct": 0.0,
    "totalPct": 1.98
  },
  "volume3": {
    "title": "Volume III \u2014 The River of Time",
    "draftWords": 0,
    "draftPct": 0.0,
    "rc1Pct": 0.0,
    "rc2Pct": 0.0,
    "goldPct": 0.0,
    "totalPct": 0.0
  },
  "globalProgress": 18.92
};
window.KILLTIME_VOL1_CHAPTERS = [
  {
    "num": 0,
    "label": "Haven't started yet",
    "title": "Haven't started yet",
    "parts": []
  },
  {
    "num": 1,
    "label": "Ch 1: The Atomic Crucible",
    "title": "The Atomic Crucible",
    "parts": []
  },
  {
    "num": 2,
    "label": "Ch 2: Echoes of the Storm",
    "title": "Echoes of the Storm",
    "parts": []
  },
  {
    "num": 3,
    "label": "Ch 3: The Kinetic Delta",
    "title": "The Kinetic Delta",
    "parts": [
      {
        "part": 1,
        "id": "chapter-3-part-1",
        "label": "Chapter 3 - Part 1: The Unmonitored Variable"
      },
      {
        "part": 2,
        "id": "chapter-3-part-2",
        "label": "Chapter 3 - Part 2: Discharge Protocol"
      },
      {
        "part": 3,
        "id": "chapter-3-part-3",
        "label": "Chapter 3 - Part 3: The Ghost and the Void"
      },
      {
        "part": 4,
        "id": "chapter-3-part-4",
        "label": "Chapter 3 - Part 4: Thermodynamic Friction"
      },
      {
        "part": 5,
        "id": "chapter-3-part-5",
        "label": "Chapter 3 - Part 5: The Kinetic Delta"
      }
    ]
  },
  {
    "num": 4,
    "label": "Ch 4: The Outlier Variables",
    "title": "The Outlier Variables",
    "parts": [
      {
        "part": 1,
        "id": "chapter-4-part-1",
        "label": "Chapter 4 - Part 1: The Gilded Current"
      },
      {
        "part": 2,
        "id": "chapter-4-part-2",
        "label": "Chapter 4 - Part 2: The Gravity of Iron"
      },
      {
        "part": 3,
        "id": "chapter-4-part-3",
        "label": "Chapter 4 - Part 3: The Friction of the World"
      }
    ]
  },
  {
    "num": 5,
    "label": "Ch 5: The Resonance of Friction",
    "title": "The Resonance of Friction",
    "parts": [
      {
        "part": 1,
        "id": "chapter-5-part-1",
        "label": "Chapter 5 - Part 1: The Acoustic Void"
      },
      {
        "part": 2,
        "id": "chapter-5-part-2",
        "label": "Chapter 5 - Part 2: The Kinetic Intersection"
      },
      {
        "part": 3,
        "id": "chapter-5-part-3",
        "label": "Chapter 5 - Part 3: The Calculus of the Spark"
      },
      {
        "part": 4,
        "id": "chapter-5-part-4",
        "label": "Chapter 5 - Part 4: Stepping into the Light"
      },
      {
        "part": 5,
        "id": "chapter-5-part-5",
        "label": "Chapter 5 - Part 5: The Unseen Sparks"
      }
    ]
  },
  {
    "num": 6,
    "label": "Ch 6: The Anatomy of a Spark",
    "title": "The Anatomy of a Spark",
    "parts": [
      {
        "part": 1,
        "id": "chapter-6-part-1",
        "label": "Chapter 6 - Part 1: The Acoustic Breach"
      },
      {
        "part": 2,
        "id": "chapter-6-part-2",
        "label": "Chapter 6 - Part 2: The Kinetic Merge"
      },
      {
        "part": 3,
        "id": "chapter-6-part-3",
        "label": "Chapter 6 - Part 3: Sleepwalking Carnage"
      },
      {
        "part": 4,
        "id": "chapter-6-part-4",
        "label": "Chapter 6 - Part 4: The Anchor of Iron"
      }
    ]
  },
  {
    "num": 7,
    "label": "Ch 7: The Perimeter Breach",
    "title": "The Perimeter Breach",
    "parts": [
      {
        "part": 1,
        "id": "chapter-7-part-1",
        "label": "Chapter 7 - Part 1: Orbital Friction"
      },
      {
        "part": 2,
        "id": "chapter-7-part-2",
        "label": "Chapter 7 - Part 2: Terminal Velocity"
      }
    ]
  },
  {
    "num": 8,
    "label": "Ch 8: The Deep Green Void",
    "title": "The Deep Green Void",
    "parts": [
      {
        "part": 1,
        "id": "chapter-8-part-1",
        "label": "Chapter 8 - Part 1: The Mountain's Root"
      },
      {
        "part": 2,
        "id": "chapter-8-part-2",
        "label": "Chapter 8 - Part 2: Shadows and Giants"
      }
    ]
  },
  {
    "num": 9,
    "label": "Ch 9: The Labyrinth of Rust",
    "title": "The Labyrinth of Rust",
    "parts": [
      {
        "part": 1,
        "id": "chapter-9-part-1",
        "label": "Chapter 9 - Part 1: The Acoustic Void"
      },
      {
        "part": 2,
        "id": "chapter-9-part-2",
        "label": "Chapter 9 - Part 2: Kinetic Momentum"
      }
    ]
  },
  {
    "num": 10,
    "label": "Ch 10: The Weight of the Shadows",
    "title": "The Weight of the Shadows",
    "parts": [
      {
        "part": 1,
        "id": "chapter-10-part-1",
        "label": "Chapter 10 - Part 1: Terminal Velocity"
      },
      {
        "part": 2,
        "id": "chapter-10-part-2",
        "label": "Chapter 10 - Part 2: The Mathematical Impossibility"
      },
      {
        "part": 3,
        "id": "chapter-10-part-3",
        "label": "Chapter 10 - Part 3: The Sterile Extraction"
      },
      {
        "part": 4,
        "id": "chapter-10-part-4",
        "label": "Chapter 10 - Part 4: The Anchor's Burden"
      },
      {
        "part": 5,
        "id": "chapter-10-part-5",
        "label": "Chapter 10 - Part 5: Beneath the Serran Sky"
      }
    ]
  },
  {
    "num": 11,
    "label": "Ch 11: The Mountain's Shadow",
    "title": "The Mountain's Shadow",
    "parts": [
      {
        "part": 1,
        "id": "chapter-11-part-1",
        "label": "Chapter 11 - Part 1: The White Abyss"
      },
      {
        "part": 2,
        "id": "chapter-11-part-2",
        "label": "Chapter 11 - Part 2: The Apex Instinct"
      },
      {
        "part": 3,
        "id": "chapter-11-part-3",
        "label": "Chapter 11 - Part 3: The Shifting Currents"
      },
      {
        "part": 4,
        "id": "chapter-11-part-4",
        "label": "Chapter 11 - Part 4: Predators of the Deep"
      },
      {
        "part": 5,
        "id": "chapter-11-part-5",
        "label": "Chapter 11 - Part 5: The Gilded Cage"
      }
    ]
  },
  {
    "num": 12,
    "label": "Ch 12: The Iron Path",
    "title": "The Iron Path",
    "parts": [
      {
        "part": 1,
        "id": "chapter-12-part-1",
        "label": "Chapter 12 - Part 1: Sparks in the Void"
      },
      {
        "part": 2,
        "id": "chapter-12-part-2",
        "label": "Chapter 12 - Part 2: The Weight of the Stone"
      },
      {
        "part": 3,
        "id": "chapter-12-part-3",
        "label": "Chapter 12 - Part 3: Toxic Resonance"
      },
      {
        "part": 4,
        "id": "chapter-12-part-4",
        "label": "Chapter 12 - Part 4: The Treacherous Vector"
      },
      {
        "part": 5,
        "id": "chapter-12-part-5",
        "label": "Chapter 12 - Part 5: The Resonance of the Sent Ones"
      }
    ]
  },
  {
    "num": 13,
    "label": "Ch 13: The Hollowed Aegis",
    "title": "The Hollowed Aegis",
    "parts": [
      {
        "part": 1,
        "id": "chapter-13-part-1",
        "label": "Chapter 13 - Part 1: Descent into the Dark"
      },
      {
        "part": 2,
        "id": "chapter-13-part-2",
        "label": "Chapter 13 - Part 2: The Apex of the Deep"
      },
      {
        "part": 3,
        "id": "chapter-13-part-3",
        "label": "Chapter 13 - Part 3: The Calculus of Treason"
      },
      {
        "part": 4,
        "id": "chapter-13-part-4",
        "label": "Chapter 13 - Part 4: The Crucible of Stone"
      }
    ]
  },
  {
    "num": 14,
    "label": "Ch 14: The Absolute Pressure",
    "title": "The Absolute Pressure",
    "parts": [
      {
        "part": 1,
        "id": "chapter-14-part-1",
        "label": "Chapter 14 - Part 1: The Bottleneck"
      },
      {
        "part": 2,
        "id": "chapter-14-part-2",
        "label": "Chapter 14 - Part 2: The Bleeding Perimeter"
      },
      {
        "part": 3,
        "id": "chapter-14-part-3",
        "label": "Chapter 14 - Part 3: The Phalanx"
      },
      {
        "part": 4,
        "id": "chapter-14-part-4",
        "label": "Chapter 14 - Part 4: The Shockwave"
      },
      {
        "part": 5,
        "id": "chapter-14-part-5",
        "label": "Chapter 14 - Part 5: Decapitation"
      }
    ]
  },
  {
    "num": 15,
    "label": "Ch 15: The Fractured Anvil",
    "title": "The Fractured Anvil",
    "parts": [
      {
        "part": 1,
        "id": "chapter-15-part-1",
        "label": "Chapter 15 - Part 1: The Crumbling Foundation"
      },
      {
        "part": 2,
        "id": "chapter-15-part-2",
        "label": "Chapter 15 - Part 2: The Imperial Missile"
      },
      {
        "part": 3,
        "id": "chapter-15-part-3",
        "label": "Chapter 15 - Part 3: Thermal Shock"
      },
      {
        "part": 4,
        "id": "chapter-15-part-4",
        "label": "Chapter 15 - Part 4: The Divergent Vector"
      },
      {
        "part": 5,
        "id": "chapter-15-part-5",
        "label": "Chapter 15 - Part 5: Terminal Mass"
      }
    ]
  },
  {
    "num": 16,
    "label": "Ch 16: Chains of Justice",
    "title": "Chains of Justice",
    "parts": [
      {
        "part": 1,
        "id": "chapter-16-part-1",
        "label": "Chapter 16 - Part 1: The Weight of the Ash"
      },
      {
        "part": 2,
        "id": "chapter-16-part-2",
        "label": "Chapter 16 - Part 2: Judgment in the Halls"
      },
      {
        "part": 3,
        "id": "chapter-16-part-3",
        "label": "Chapter 16 - Part 3: Echoes of the Trial"
      },
      {
        "part": 4,
        "id": "chapter-16-part-4",
        "label": "Chapter 16 - Part 4: The Obsidian Cipher"
      },
      {
        "part": 5,
        "id": "chapter-16-part-5",
        "label": "Chapter 16 - Part 5: Unfinished Threads"
      }
    ]
  },
  {
    "num": 17,
    "label": "Ch 17: The Gilded Shackle",
    "title": "The Gilded Shackle",
    "parts": [
      {
        "part": 1,
        "id": "chapter-17-part-1",
        "label": "Chapter 17 - Part 1: A Hero's Surveillance"
      },
      {
        "part": 2,
        "id": "chapter-17-part-2",
        "label": "Chapter 17 - Part 2: Discovery in the Lab"
      },
      {
        "part": 3,
        "id": "chapter-17-part-3",
        "label": "Chapter 17 - Part 3: Shadows of Justice"
      },
      {
        "part": 4,
        "id": "chapter-17-part-4",
        "label": "Chapter 17 - Part 4: The Envoy's Gambit"
      },
      {
        "part": 5,
        "id": "chapter-17-part-5",
        "label": "Chapter 17 - Part 5: Arrival in Haliriel"
      }
    ]
  }
];
